### ISSUE TITLE
Number Format Exception from loadGoogleModel

### ISSUE THREAD

**Issue by siminou** [NLPchina/Word2VEC_java#40]
I got a corpus.bin from https://pan.baidu.com/s/1dFKevtv . When i tried to run the test program , shows error as 
Exception in thread "main" java.lang.NumberFormatException: For input string: "中共中央"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.ansj.vec.Word2VEC.loadGoogleModel(Word2VEC.java:80)

**Comment by sakura182** [comment]
我遇见了类似的问题，请问解决了吗
