### ISSUE TITLE
请问，为什么用您的语料库会出现以下错误

### ISSUE THREAD

**Issue by ghost** [NLPchina/Word2VEC_java#43]
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2迈向	充满	希望	的	新	世纪	——	一九九八年	新年	讲话	（	附	图片	1	张	）
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1447)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1333)
	at com.alibaba.fastjson.JSON.parse(JSON.java:152)
	at com.alibaba.fastjson.JSON.parse(JSON.java:162)
	at com.alibaba.fastjson.JSON.parse(JSON.java:131)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:223)
	at tets_word_vec.Test.parserFile(Test.java:61)
	at tets_word_vec.Test.main(Test.java:29)

**Comment by inahero** [comment]
他最前面那段代码是生成语料库的，如果是直接用他提供的语料库，可以把sportCorpusFile指向那个语料库然后直接做分词训练
