### ISSUE TITLE
调用loadGoogleModel模型，产生如下报错

### ISSUE THREAD

**Issue by baymaxZ0Z0** [NLPchina/Word2VEC_java#44]
Exception in thread "main" java.lang.NumberFormatException: For input string: " �1   � 	2.2万吨��`6=+f>o��>�;b>�R=~"2�W6=��)�%������E�=s��l"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.ansj.vec.Word2VEC.loadGoogleModel(Word2VEC.java:80)
	at test.Test.main(Test.java:10)

**Comment by ansjsun** [comment]
是google 训练的model 吗？？ 不要 text的 要二进制
